# Generated by Django 5.2.15 on 2026-06-17 23:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulbacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_match_i_0311b6_idx',
            old_name='goals_match_i_1ad044_idx',
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_player__357acd_idx',
            old_name='goals_player__e52b65_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_group_i_9ab3b6_idx',
            old_name='matches_group_i_927365_idx',
        ),
    ]
