from django.urls import path

from . import admin_views, views

urlpatterns = [
    path("admin/", admin_views.dashboard, name="admin-dashboard"),
    path("admin/users/", admin_views.users, name="admin-users"),
    path("admin/users/<uuid:user_id>/", admin_views.user_detail, name="admin-user-detail"),
    path("admin/users/<uuid:user_id>/active/", admin_views.user_active, name="admin-user-active"),
    path("admin/users/<uuid:user_id>/superuser/", admin_views.user_superuser, name="admin-user-superuser"),
    path("admin/groups/", admin_views.groups, name="admin-groups"),
    path("admin/groups/<uuid:group_id>/", admin_views.group_detail, name="admin-group-detail"),
    path("admin/matches/", admin_views.matches, name="admin-matches"),
    path("admin/matches/<uuid:match_id>/", admin_views.match_detail, name="admin-match-detail"),
    path("", views.landing, name="landing"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("registro/", views.register, name="register"),
    path("grupos/", views.groups_index, name="groups-index"),
    path("grupos/nuevo/", views.group_create, name="group-create"),
    path("grupos/unirse/", views.group_join, name="group-join"),
    path("grupos/<uuid:group_id>/", views.group_dashboard, name="group-dashboard"),
    path("grupos/<uuid:group_id>/ajustes/", views.group_settings, name="group-settings"),
    path("grupos/<uuid:group_id>/miembros/<uuid:user_id>/rol/", views.member_role_update, name="member-role-update"),
    path("grupos/<uuid:group_id>/miembros/<uuid:user_id>/eliminar/", views.member_remove, name="member-remove"),
    path("grupos/<uuid:group_id>/jugadores/", views.players_list, name="players-list"),
    path("grupos/<uuid:group_id>/jugadores/exportar.csv", views.players_export_csv, name="players-export-csv"),
    path("grupos/<uuid:group_id>/jugadores/importar/", views.players_import_csv, name="players-import-csv"),
    path("grupos/<uuid:group_id>/jugadores/nuevo/", views.player_create, name="player-create"),
    path("grupos/<uuid:group_id>/jugadores/casuales/", views.casuals_manage, name="casuals-manage"),
    path("grupos/<uuid:group_id>/jugadores/<uuid:player_id>/", views.player_detail, name="player-detail"),
    path("grupos/<uuid:group_id>/jugadores/<uuid:player_id>/editar/", views.player_edit, name="player-edit"),
    path("grupos/<uuid:group_id>/jugadores/<uuid:player_id>/baja/", views.player_deactivate, name="player-deactivate"),
    path("grupos/<uuid:group_id>/partidos/", views.matches_list, name="matches-list"),
    path("grupos/<uuid:group_id>/partidos/exportar.csv", views.matches_export_csv, name="matches-export-csv"),
    path("grupos/<uuid:group_id>/partidos/importar/", views.matches_import_csv, name="matches-import-csv"),
    path("grupos/<uuid:group_id>/partidos/nuevo/", views.match_create, name="match-create"),
    path("grupos/<uuid:group_id>/partidos/<uuid:match_id>/", views.match_detail, name="match-detail"),
    path("grupos/<uuid:group_id>/partidos/<uuid:match_id>/editar/", views.match_edit, name="match-edit"),
    path("invitado/", views.guest_code, name="guest-code"),
    path("invitado/<str:code>/", views.guest_dashboard, name="guest-dashboard"),
    path("invitado/<str:code>/jugadores/", views.guest_players, name="guest-players"),
    path("invitado/<str:code>/jugadores/<uuid:player_id>/", views.guest_player_detail, name="guest-player-detail"),
    path("invitado/<str:code>/partidos/", views.guest_matches, name="guest-matches"),
    path("invitado/<str:code>/partidos/<uuid:match_id>/", views.guest_match_detail, name="guest-match-detail"),
]
